name: licham
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: http://amlich.demen.org
# author: Thai Huynh <thaihuynhxyz@gmail.com>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  intl: ^0.17.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^2.1.11

flutter:
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf
  uses-material-design: true