name: licham
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: http://www.lich.am
# author: Thai Huynh <thaihuynhxyz@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha+22
  http: ^0.12.0
  font_awesome: ^4.7.0+1

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1
