name: licham
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: http://amlich.demen.org
# author: Thai Huynh <thaihuynhxyz@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter_web: any
  flutter_web_ui: any

dev_dependencies:
  build_runner: ^1.5.2
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  test: ^1.6.1

# flutter_web packages are not published to pub.dartlang.org
# These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui